### ISSUE TITLE
seen and first-seen issues

### ISSUE THREAD

**Issue by MillerBoss** [funsocietyirc/MrNodeBot#33]
In channel
10:14:02 PM  Jack	`seen Amy
10:14:03 PM  +layer-eight	I need someone to look for Jack

10:14:07 PM  Jack	`seen Amy Amy
10:14:08 PM  +layer-eight	Seen →  Amy Saying tcl wtf for? via Log on #channel 3 hours ago

#channel only allows identified users so Jack is identified with NickServ.
10:19:59 PM -NickServ-	Jack ACC 3 
https://github.com/funsocietyirc/MrNodeBot/blob/master/config.sample.js#L152 is set to 3

Jack can do the command as an OP or regular user and have the same issue. Jack is also an admin of the bot.
If the owner, me, runs `seen Amy it works fine in #channel and I can be either regular user, voice, or OP.

The same issue persists if `first-seen <nick> is ran, but

If `first-seen MillerBoss is done:

06:49:41 PM  MillerBOSS	`first-seen MillerBoss
06:49:41 PM  layer-eight	Seen →  MillerBOSS Saying Layer-9 update via Log on #boats2 21 days ago → Changing their nick to MillerBoss on [#boats2] 13 days ago → additional results have been messaged to you MillerBOSS
Then the bot messaging me non-stop with:
06:49:42 PM  layer-eight	Then saying Layer-9 update via Log on #boats2 21 days ago → Changing their nick to MillerBoss on [#boats2] 13 days ago
06:49:43 PM  layer-eight	Then saying Layer-9 update via Log on #boats2 21 days ago → Changing their nick to MillerBoss on [#boats2] 13 days ago
06:49:43 PM  layer-eight	Then saying Layer-9 update via Log on #boats2 21 days ago → Changing their nick to MillerBoss on [#boats2] 13 days ago
06:49:43 PM  layer-eight	Then saying Layer-9 update via Log on #boats2 21 days ago → Changing their nick to MillerBoss on [#boats2] 13 days ago
06:49:44 PM  layer-eight	Then saying Layer-9 update via Log on #boats2 21 days ago → Changing their nick to MillerBoss on [#boats2] 13 days ago
06:49:45 PM  layer-eight	Then saying Layer-9 update via Log on #boats2 21 days ago → Changing their nick to MillerBoss on [#boats2] 13 days ago
06:49:45 PM  layer-eight	Then saying Layer-9 update via Log on #boats2 21 days ago → Changing their nick to MillerBoss on [#boats2] 13 days ago
06:49:46 PM  layer-eight	Then saying Layer-9 update via Log on #boats2 21 days ago → Changing their nick to MillerBoss on [#boats2] 13 days ago
06:49:46 PM  layer-eight	Then saying Layer-9 update via Log on #boats2 21 days ago → Changing their nick to MillerBoss on [#boats2] 13 days ago
06:49:47 PM  layer-eight	Then saying Layer-9 update via Log on #boats2 21 days ago → Changing their nick to MillerBoss on [#boats2] 13 days ago
06:49:47 PM  layer-eight	Then saying Layer-9 update via Log on #boats2 21 days ago → Changing their nick to MillerBoss on [#boats2] 13 days ago
06:49:47 PM  layer-eight	Then saying Layer-9 update via Log on #boats2 21 days ago → Changing their nick to MillerBoss on [#boats2] 13 days ago
06:49:47 PM  layer-eight	Then saying Layer-9 update via Log on #boats2 21 days ago → Changing their nick to MillerBoss on [#boats2] 13 days ago
06:49:47 PM  layer-eight	Then saying Layer-9 update via Log on #boats2 21 days ago → Changing their nick to MillerBoss on [#boats2] 13 days ago
Then I need to CTRL + C in the terminal window and the quit message of the bot is excess flood.

Turn down audio to see log https://millerboss.com/x/Screen-Recording-2018-05-10-01-08-13-D1.mp4
I was jamming to Dice while recording.

Here is git diff. MrNodeBot is in /root/MrNodeBot This is more or less a test  instance.
https://gist.github.com/MillerBoss/2401ce9552d72ce4b9e0d0e12095e8a6

**Comment by davericher** [comment]
Curious, is I know jack is identified, but is he on his actual primary nick or a grouped nick

**Comment by MillerBoss** [comment]
Actual primary nick. This happens to anyone that attempts the `seen or `first-seen command.

And again, the channel that was giving a nice testing to the bot only allows identified users to join the channel.
