### ISSUE TITLE
Pasted URL error

### ISSUE THREAD

**Issue by MillerBoss** [funsocietyirc/MrNodeBot#34]
In channel https://www.amazon.com/gp/product/B01M20VBU7/ is pasted. 
No output from bot. This happens rarely. 
Debug console shows:
knex:query insert into `logging` (`from`, `host`, `ident`, `text`, `timestamp`, `to`) values (?, ?, ?, ?, ?, ?) undefined +4m
  knex:bindings [ 'MillerBOSS',
  knex:bindings   'cyber.cyber.cyber.cyber.cyber.cyber.cyber.millerboss.com',
  knex:bindings   '~shit',
  knex:bindings   'https://www.amazon.com/gp/product/B01M20VBU7/',
  knex:bindings   2018-05-12T05:09:11.493Z,
  knex:bindings   '#boats2' ] undefined +4m
  knex:client releasing connection to pool: __knexUid48 +4ms
2018-05-12T05:09:11.605Z - warn: Error in URL Listener chain
{ err: '405 - ""',
  stack: 'StatusCodeError: 405 - ""\n    at new StatusCodeError (/root/MrNodeBot/node_modules/request-promise-core/lib/errors.js:32:15)\n    at /root/MrNodeBot/node_modules/request-promise-core/lib/plumbing.js:97:41\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' }

**Comment by davericher** [comment]
This is actually due to amazons anti parsing stuff, no way around this unless we switch to something like phantomjs and do it headless, which would have HUGE overhead.

If anyone can figure out how to get around amazon and their anti scraping, I am all ears!

**Comment by MillerBoss** [comment]
I run Cloudbot as well. I am unsure if this helps at all. https://github.com/CloudBotIRC/CloudBot/blob/master/plugins/amazon.py

Example:

11:43:58 AM  +MillerBOSS	 https://www.amazon.com/gp/product/B01M20VBU7/
11:44:00 AM  @HEYYOUGUYS	(+MillerBOSS) Samsung 960 EVO Series - 500GB NVMe - M.2 Internal SSD... ($218.76) - 4.7/5 stars (1,566 ratings) - Prime, Free Shipping
