### ISSUE TITLE
Found a bug

### ISSUE THREAD

**Issue by MillerBoss** [funsocietyirc/MrNodeBot#41]
10:53:24 AM M<MillerBoss> MrNodeBot: definition iff
10:53:26 AM ⇐ @MrNodeBot quit (~MrNodeBot@unaffiliated/irony/bot/mrnodebot) Quit: Something has gone seriously wrong, hopefully I will return!
10:53:33 AM M<MillerBoss> Found a bug
10:53:43 AM → @MrNodeBot (opped) joined

**Comment by davericher** [comment]
Seems to be resolved
